Fix Finding Report

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -61,8 +61,21 @@ jobs:
           cd /opt/Autonomy_Software/build
           ctest -T Coverage --build-config RelWithDebInfo
 
+      - name: Organize Files
+        run: |
+          cd /opt/Autonomy_Software/
+          coverage_file=$(find . -name "Coverage.xml" | head -n 1)
+          if [ -f "$coverage_file" ]; then
+            mv "$coverage_file" /opt/Autonomy_Software/build
+          else
+            echo "Coverage.xml not found"
+            exit 1
+          fi
+
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           verbose: true
+          directory: /opt/Autonomy_Software/build
+          file: Coverage.xml
