Fix Coverage Test

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -63,15 +63,23 @@ jobs:
           cd /opt/Autonomy_Software/build
           ctest -T Test -T Coverage
 
-      - name: Organize Files
+      - name: Move Coverage Files
         run: |
           cd /opt/Autonomy_Software/
-          ls -alR build/
+
           coverage_file=$(find . -name "Coverage.xml" | head -n 1)
           if [ -f "$coverage_file" ]; then
             mv "$coverage_file" /opt/Autonomy_Software/build
           else
             echo "Coverage.xml not found"
+            exit 1
+          fi
+
+          test_file=$(find . -name "Test.xml" | head -n 1)
+          if [ -f "$test_file" ]; then
+            mv "$test_file" /opt/Autonomy_Software/build
+          else
+            echo "Test.xml not found"
             exit 1
           fi
 
@@ -82,3 +90,12 @@ jobs:
           verbose: true
           directory: /opt/Autonomy_Software/build
           file: Coverage.xml
+
+      - name: Upload test results to Codecov
+        if: ${{ !cancelled() }}
+        uses: codecov/test-results-action@v1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          verbose: true
+          directory: /opt/Autonomy_Software/build
+          file: Test.xml
